### ISSUE TITLE
Multiple cloud mounts in unionfs

### ISSUE THREAD

**Issue by lex8888** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#558]
**Is your feature request related to a problem? No

**Describe the feature/solution you'd like**
Would it be difficult to add multiple mounts into unionfs as a feature in pg setup/menu?   e.g. If you have content in a couple of different locations/accounts, let you mount gdrive, gdrive2, tdrive3 with all merging in unionfs?  The objective would be to let plex/emby etc read from the multiple mounts in unionfs.   For uploads, if  'move' needs to point to a single account/mount then have it point at gdrive.
So a menu item would say something like  "How many remote drives would you like to mount?" ... or "Add a remote mount"

**Additional context**

**Comment by Admin9705** [comment]
ya that won't happen for this project because of it's difficulty in programming implementation. PG is meant for your gdrive and your tdrive.   the idea sounds simple, but the complexity of this becomes a nightmare :D .... but you can always fork the project an attempt this :D I'm just being honest :D
