### ISSUE TITLE
Storage is full.

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#85]
I've restarted the server and containers. Updated and reinstalled plexguide, did the preinstall again and entered the rclone setup and backed out. 

The rclone and plexdrive test both show my files.

**Comment by Admin9705** [comment]
ya i wouldn't know where to approach this angle. reason is because you'll have to check to see if your move service is working. a misconfigured directory is usually a reason or you didn't reserve a min space in SAB or NZBGET.  Basicailly the upload is capped at 9MB, so if your DL is faster (which most likely is) it will get full.  The upload over time will clear space.

**Comment by AugusDogus** [comment]
I set the minimum allowed space in SAB and it was working great for a while. It's currently set at 30GB, but reads that there's 0 B Free Space and this is true on my VPS control panel as well. 

Downloads and automatic uploads from sonarr and radarr and requests from ombi were working great for a few days, but 4 days ago they stopped working.

**Comment by AugusDogus** [comment]
How can I check if my move service is working?

**Comment by AugusDogus** [comment]
Is the best/recommended way to fix this backup and start again? @Admin9705

**Comment by Admin9705** [comment]
@AugusDogus try the latest update, we did a ton of chmoding :D

**Comment by AugusDogus** [comment]
Seeing as there have been some fundamental changes with plexguide I'm going to do my best to backup what I can and reinstall. Please view this issue as closed as the version has been deprecated.
